name: Modmail Workflow

on: [push, pull_request]

jobs:
  code-style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    name: Python ${{ matrix.python-version }} on ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev --system
    # to refresh: bandit -f json -o .bandit_baseline.json -r . 
    # - name: Bandit syntax check
    #   run: bandit -r . -b .bandit_baseline.json
    - name: Pylint
      run: pylint ./bot.py cogs/*.py core/*.py  --exit-zero -r y
      continue-on-error: true
    - name: Black
      run: |
        black . --diff --check
